# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [12]:
'''
list()  = 用於將tuple轉換成list，故當一個array使用list()進行轉換的話，只能把數據中最外一層進行列表轉換

tolist() = 把數組或是矩陣轉換成list的形式，故array使用tolist()可以把數據全部list化



note:
tuple = 元組
list = 列表
array = 陣列

'''

'\nlist()  = 用於將tuple轉換成list，故當一個array使用list()進行轉換的話，只能把數據中最外一層進行列表轉換\n\ntolist() = 把數組或是矩陣轉換成list的形式，故array使用tolist()可以把數據全部list化\n\n\n\nnote:\ntuple = 元組\nlist = 列表\narray = 陣列\n\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

import numpy as np 

In [10]:

a = np.random.randint(10, size=6) 

print(a)

##ndim = 陣列維度
print("ndim:",a.ndim)

##shape = 每個維度的大小
print("shape:",a.shape)

##size = 陣列當中的元素個數
print("size:",a.size)

##dtype = 陣列中的資料型態
print("dtype:",a.dtype)

##itemsize = 陣列中每個元素所占用的空間
print("itemsize:",a.itemsize)

##len = 返回對象之長度
print('length: ',len(a))

##type = 顯示類別
print('type:', type(a))


'''
解釋:
1. 資料為一維度 (ndim: 1) 
2. 每個維度的大小為6 (shape: (6,))
3. 元素個素為6 (size: 6)
4. 資料型態為32位元整數 (dtype: int32)
5. 陣列中每個元素所占用的空間為4 (itemsize: 4)
6. 陣列長度為6 (length:  6)
7. 資料型態為陣列 (data:  <class 'numpy.ndarray'>)

'''

[2 4 0 2 9 6]
ndim: 1
shape: (6,)
size: 6
dtype: int32
itemsize: 4
length:  6
type: <class 'numpy.ndarray'>


"\n解釋:\n1. 資料為一維度 (ndim: 1) \n2. 每個維度的大小為6 (shape: (6,))\n3. 元素個素為6 (size: 6)\n4. 資料型態為32位元整數 (dtype: int32)\n5. 陣列中每個元素所占用的空間為4 (itemsize: 4)\n6. 陣列長度為6 (length:  6)\n7. 資料型態為陣列 (data:  <class 'numpy.ndarray'>)\n\n"

In [9]:
b = np.random.randint(10, size=(3,4)) 

print(b)

##ndim = 陣列維度
print("ndim:",b.ndim)

##shape = 每個維度的大小
print("shape:",b.shape)

##size = 陣列當中的元素個數
print("size:",b.size)

##dtype = 陣列中的資料型態
print("dtype:",b.dtype)

##itemsize = 陣列中每個元素所占用的空間
print("itemsize:",b.itemsize)

##len = 返回對象之長度
print('length: ',len(b))

##type = 顯示類別
print('type:', type(b))


'''
解釋:
1. 資料為2維度 (ndim: 2) 
2. 為一個3x4矩陣 (shape: (3,4))
3. 元素個素為12 (size: 12)
4. 資料型態為32位元整數 (dtype: int32)
5. 陣列中每個元素所占用的空間為4 (itemsize: 4)
6. 陣列長度為3 (length:  3)
7. 資料型態為陣列 (data:  <class 'numpy.ndarray'>)

'''

[[0 7 5 4]
 [6 6 3 4]
 [7 4 6 1]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int32
itemsize: 4
length:  3
type: <class 'numpy.ndarray'>


"\n解釋:\n1. 資料為2維度 (ndim: 2) \n2. 為一個3x4矩陣 (shape: (3,4))\n3. 元素個素為12 (size: 12)\n4. 資料型態為32位元整數 (dtype: int32)\n5. 陣列中每個元素所占用的空間為4 (itemsize: 4)\n6. 陣列長度為3 (length:  3)\n7. 資料型態為陣列 (data:  <class 'numpy.ndarray'>)\n\n"

In [11]:
c = np.random.randint(10, size=(2,3,2)) 


print(c)

##ndim = 陣列維度
print("ndim:",c.ndim)

##shape = 每個維度的大小
print("shape:",c.shape)

##size = 陣列當中的元素個數
print("size:",c.size)

##dtype = 陣列中的資料型態
print("dtype:",c.dtype)

##itemsize = 陣列中每個元素所占用的空間
print("itemsize:",c.itemsize)

##len = 返回對象之長度
print('length: ',len(c))

##type = 顯示類別
print('type:', type(c))


'''
解釋:
1. 資料為3維度 (ndim: 3) 
2. 為2個3x2矩陣 (shape: (2, 3, 2))
3. 元素個素為12 (size: 12)
4. 資料型態為32位元整數 (dtype: int32)
5. 陣列中每個元素所占用的空間為4 (itemsize: 4)
6. 陣列長度為2 (length:  2)
7. 資料型態為陣列 (data:  <class 'numpy.ndarray'>)

'''

[[[9 2]
  [1 9]
  [3 4]]

 [[5 7]
  [3 4]
  [8 3]]]
ndim: 3
shape: (2, 3, 2)
size: 12
dtype: int32
itemsize: 4
length:  2
type: <class 'numpy.ndarray'>


"\n解釋:\n1. 資料為2維度 (ndim: 2) \n2. 為一個3x4矩陣 (shape: (3,4))\n3. 元素個素為12 (size: 12)\n4. 資料型態為32位元整數 (dtype: int32)\n5. 陣列中每個元素所占用的空間為4 (itemsize: 4)\n6. 陣列長度為3 (length:  3)\n7. 資料型態為陣列 (data:  <class 'numpy.ndarray'>)\n\n"

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [2]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[4, 0, 3, 9, 2, 8]
[4, 0, 3, 9, 2, 8]


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[0, 6, 8, 5], [2, 3, 3, 2], [7, 7, 3, 7]]
[array([0, 6, 8, 5]), array([2, 3, 3, 2]), array([7, 7, 3, 7])]


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[5, 2], [3, 6], [8, 4]], [[4, 3], [7, 2], [0, 9]]]
[array([[5, 2],
       [3, 6],
       [8, 4]]), array([[4, 3],
       [7, 2],
       [0, 9]])]


In [75]:
def tolist(iterable):
    list_empty = [] 
    dim = iterable.ndim
    if dim ==1 :
        return (list(iterable))
    elif dim ==2 :
        for i in range(iterable.shape[0]):
            temp = list(list(iterable)[i])
            list_empty.append(temp)
        return (list_empty)
    else :
        for i in range(iterable.shape[0]):
            for j in range(iterable.shape[1]):
                temp = list(list(iterable)[i][j])
                list_empty.append(temp)
        return(list_empty)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 0, 3, 9, 2, 8]
[[0, 6, 8, 5], [2, 3, 3, 2], [7, 7, 3, 7]]
[[5, 2], [3, 6], [8, 4], [4, 3], [7, 2], [0, 9]]
